### ISSUE TITLE
Failing without message

### ISSUE THREAD

**Issue by mydea** [github/update-project-action#170]
I am trying to run this e.g. here: https://github.com/getsentry/sentry-javascript/actions/runs/10738050627/job/29780825352?pr=13608, but it fails without any error message.

It seems to log out the whole action code, and then

> ##[debug]Node Action run completed with exit code 1

**Comment by benbalter** [comment]
@mydea If you re-run the job with `@main` (instead of `@v3`), you should now be able to see the error message.

Context: Previously the Action was minified, which caused the backtrace to spit out the entire source code (including dependencies), since it was all on one line. This presumably hit an output limit within GitHub Actions. I unminified the Action, which in my testing makes the true error visible.

**Comment by mydea** [comment]
Ah yes, that is working now - thank you! 🙏
